EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"
LLM_PATH = "models/qwen2.5-3b-instruct-q5_k_m.gguf"
INPUT_RAW_EXCEL_PATH = "/path/to/movie_dataset.csv"
INPUT_EXCEL_PATH = "/path/to/cleaned_movie_dataset.csv"
FAISS_STORE_DIR = "faiss_store"