EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"
LLM_PATH = "models/gemma-3-4b-it-q4_0.gguf"
INPUT_RAW_EXCEL_PATH = "/home/omkanekar28/code/RAG-Implementation/data/movie_dataset.csv"
INPUT_EXCEL_PATH = "/home/omkanekar28/code/RAG-Implementation/data/cleaned_movie_dataset.csv"
FAISS_STORE_DIR = "/home/omkanekar28/code/RAG-Implementation/data/faiss_store"